gateway_api_version: "v1.4.1"
gateway_api_base_url: "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{ gateway_api_version }}/config/crd/standard"
gateway_api_experimental_base_url: "https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/{{ gateway_api_version }}/config/crd/experimental"
