# inventory/hosts

[all]
srv-rk1-01 ansible_host=192.168.178.133
srv-super6-cm4-emmc-01 ansible_host=192.168.178.105

[server_nodes]
srv-rk1-01

[agent_nodes]
srv-super6-cm4-emmc-01 

[k3s_nodes:children]
server_nodes
agent_nodes

[all:vars]
ansible_user=dalmine
ansible_ssh_private_key_file=~/.ssh/id_ed25519
