# inventory/hosts

[all]
srv-super6c-04-emmc ansible_host=192.168.178.133
srv-super6c-01-nvme ansible_host=192.168.178.85
srv-super6c-02-nvme ansible_host=192.168.178.86
srv-super6c-03-nvme ansible_host=192.168.178.87
srv-pi4-sd-01 ansible_host=192.168.178.40
srv-rk1-nvme-01 ansible_host=192.168.178.30
srv-rk1-nvme-02 ansible_host=192.168.178.48
srv-rk1-nvme-03 ansible_host=192.168.178.51
srv-rk1-nvme-04 ansible_host=192.168.178.59

[server_nodes]
srv-super6c-04-emmc

[agent_nodes]
srv-pi4-sd-01
srv-super6c-01-nvme
srv-super6c-02-nvme
srv-super6c-03-nvme
srv-rk1-nvme-01
srv-rk1-nvme-02
srv-rk1-nvme-03
srv-rk1-nvme-04

[k3s_nodes:children]
server_nodes
agent_nodes

[all:vars]
ansible_user=dalmine
ansible_ssh_private_key_file=~/.ssh/id_ed25519
