apiVersion: v1
kind: Service
metadata:
  name: {{ include "honcho.fullname" . }}-api
  labels:
    {{- include "honcho.labels" . | nindent 4 }}
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "honcho.selectorLabels" . | nindent 4 }}
    app: {{ include "honcho.fullname" . }}-api
  type: ClusterIP
