loki_version: "6.55.0"
loki_namespace: monitoring
loki_deployment_mode: SingleBinary
loki_replicas: 1
loki_minio_enabled: true
loki_storage_size: 1Gi
loki_minio_persistence_size: 1Gi
loki_storage_retention_period: 24h  # 1 day — CM4 has limited storage
loki_chunks_cache_enabled: false
loki_results_cache_enabled: false
