{{- if eq .Values.auth.mode "basic" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nas-admin.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nas-admin.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.basic.username | quote }}
  password: {{ .Values.auth.basic.password | quote }}
{{- end }}
{{- if eq .Values.auth.mode "oidc" }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nas-admin.fullname" . }}-oidc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nas-admin.labels" . | nindent 4 }}
type: Opaque
stringData:
  clientId: {{ .Values.auth.oidc.clientId | quote }}
  clientSecret: {{ .Values.auth.oidc.clientSecret | quote }}
  cookieSecret: {{ .Values.auth.oidc.cookieSecret | quote }}
{{- end }}
