---
- name: Add csi-driver-smb helm repo
  kubernetes.core.helm_repository:
    name: csi-driver-smb
    repo_url: https://kubernetes-sigs.github.io/smb-csi
  register: csi_repo
  ignore_errors: true

- name: Install or upgrade csi-driver-smb
  kubernetes.core.helm:
    name: csi-driver-smb
    chart_ref: csi-driver-smb/csi-driver-smb
    chart_version: "1.20.1"
    release_namespace: kube-system
    create_namespace: false
    values: {}
  register: csi_install
  failed_when: false
