litellm_proxy_version: "main-latest"
litellm_namespace: ai
litellm_master_key: "sk-hermes-internal"
litellm_port: 4000
litellm_cpu_request: "100m"
litellm_cpu_limit: "500m"
litellm_memory_request: "512Mi"
litellm_memory_limit: "3Gi"
