kube_prometheus_stack_version: "82.18.0"
kube_prometheus_stack_namespace: monitoring
kube_prometheus_stack_hostname: grafana.cluster.home
kube_prometheus_stack_admin_password: admin
kube_prometheus_stack_storage_class: smb-nas
kube_prometheus_stack_storage_size: "20Gi"
